In [1]:
import numpy as np

In [15]:
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [17]:
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [20]:
B = A[1:4, 0:3]
print(B)

In [22]:
C = A[::2]
print(C)

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [26]:
my_array = np.array([[1,2,3],[2,3,4],[2,5,6]])

In [27]:
np.linalg.det(my_array)

2.0

In [28]:
1*(3*6-4*5)-2*(2*6-4*2)+3*(2*5-3*2)

2

In [ ]:
[[1,2,3],[2,4,6],[2,5,6]]

In [30]:
1*(4*6-6*5)-2*(2*6-6*2)+3*(2*5-4*2)

0

In [32]:
my_array_2 = [[1,2,3],[2,3,4],[2,5,6]]

In [33]:
np.linalg.det(my_array_2)

2.0

In [ ]:
[[1,2,3],[2,3,4],[2,5,6]]

In [31]:
1*(3*6-4*5)-2*(2*6-4*2)+3*(2*5-3*2)

2

In [35]:
np.linalg.inv(my_array_2)

array([[-1. ,  1.5, -0.5],
       [-2. ,  0. ,  1. ],
       [ 2. , -0.5, -0.5]])

In [20]:
new_array=[[1,2,3],[2,3,4],[4,6,8]]

In [21]:
np.trace(new_array)

12

In [22]:
np.linalg.det(new_array)

0.0

In [34]:
1*(3*8-4*6)-2*(2*8-4*4)+3*(2*6-3*4)

0