In [1]:
import numpy as np

In [15]:
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [17]:
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [20]:
B = A[1:4, 0:3]
print(B)

In [22]:
C = A[::2]
print(C)

[[ 1  2  3  4]
 [ 9 10 11 12]]
