In [2]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10,size=6) # One- dimensional array
x2 = np.random.randint(10,size=(3,4)) # Two- dimensional array
x3 = np.random.randint(10,size=(3,4,5)) # Three- dimensional array

In [3]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", )

x3 ndim:  3


Numpy array slicing differs from Python list slicing: in lists, slices will be copies. Consider our two-dimensional array from before:

In [4]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


Let's extract a 2x2 subarray from this

In [5]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[3 5]
 [7 6]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [6]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [8]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# Creating copies of arrays

In [9]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


If we now modify this subarray, the original array is not touched:

In [10]:
x2_sub_copy[0,0]=42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [11]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# Reshaping Of Arrays

In [12]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Or use newaxis keyword

In [13]:
x = np.array([1,2,3])

# row vector via reshape
x.reshape((1,3))

array([[1, 2, 3]])

In [14]:
# row vector via newaxis
x[np.newaxis,:]

array([[1, 2, 3]])

# Concatenation of array

In [18]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [19]:
z = [99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


Can be used for two-dimensional arrays:

In [20]:
grid = np.array([[1,2,3],[4,5,6]])

In [21]:
# concatenate along the first axis
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [22]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, can be clearer to use the np.vstack (vertical stacking)

In [26]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])

np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [35]:
new_grid = np.array([[99],[99]])

np.hstack((grid,new_grid))

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

# Splitting of arrays

In [27]:
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


# Array arithmetic

In [48]:
x = np.arange(4)

print("x           = ", x)
print("x+5         = ", x+5)
print("x-5         = ", x-5)
print("x*5         = ", x*5)
print("x/5         = ", x/5)

# floor division
print("x//5         = ", x//2)


x           =  [0 1 2 3]
x+5         =  [5 6 7 8]
x-5         =  [-5 -4 -3 -2]
x*5         =  [ 0  5 10 15]
x/5         =  [0.  0.2 0.4 0.6]
x//5         =  [0 0 1 1]
