In [5]:
#import pandas as pd
import csv as csv
import numpy as np

In [6]:
df2=pd.read_csv('AAPL_stock_price_example.csv', index_col=0)

NameError: name 'pd' is not defined

In [ ]:
df2

In [ ]:
with open('AAPL_stock_price_example.csv') as csvfile:
    reader = csv.DictReader(csvfile)
    
    print(reader.fieldnames)
    
    data = []
    for row in reader:
        data.append(row)
    
    print(data)

In [7]:
a = np.arange(5)

In [8]:
a.dtype

dtype('int32')

In [9]:
a

array([0, 1, 2, 3, 4])

In [10]:
a.shape

(5,)

In [13]:
m = np.array([np.arange(2),np.arange(2)])

In [14]:
m

array([[0, 1],
       [0, 1]])

In [15]:
m.shape

(2, 2)

In [16]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [17]:
np.array?

In [18]:
a = np.array([[1,2],[3,4]])

In [19]:
a

array([[1, 2],
       [3, 4]])