In [35]:
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib as mp
import scipy as sc
import random

In [7]:
print(pd.__version__)
print(np.__version__)
print(sk.__version__)
print(mp.__version__)
print(sc.__version__)

1.1.3
1.19.2
1.1.3
3.3.2
1.9.3


In [3]:
x = np.arange(15, dtype=np.int64).reshape(3,5)
x[1:, ::2] = -99
x

array([[  0,   1,   2,   3,   4],
       [-99,   6, -99,   8, -99],
       [-99,  11, -99,  13, -99]], dtype=int64)

In [4]:
x.max(axis=1)

array([ 4,  8, 13], dtype=int64)

In [5]:
rng = np.random.default_rng()
samples = rng.normal(size=2500)
samples

array([ 1.02585252, -0.34681911,  2.66330802, ...,  1.29804996,
       -0.79946183,  2.87624195])

In [16]:
my_first_array= np.array([1,2,3])
print(my_first_array)
print(my_first_array.shape)
print(my_first_array.size)
print(len(my_first_array))
print(my_first_array.dtype.name)
print(my_first_array.sum())
print(my_first_array.min())
print(my_first_array.max())
print(my_first_array.mean())

[1 2 3]
(3,)
3
3
int32
6
1
3
2.0


In [8]:
int_ones = np.ones((2,2),dtype=np.int8)
int_ones

array([['1', '1'],
       ['1', '1']], dtype='<U16')

In [14]:
string_arr = np.array(["Sam","Bill","Gary"], dtype="<U16")
print(string_arr)

['Sam' 'Bill' 'Gary']


In [15]:
string_arr[1]="Waldo"
print(string_arr)

['Sam' 'Waldo' 'Gary']


In [16]:
vec1 = np.array([1,-1,0],dtype=np.float16)
vec2=vec1/0
print(vec2)

[ inf -inf  nan]


<ipython-input-16-89c6bf39c27a>:2: RuntimeWarning: divide by zero encountered in true_divide
  vec2=vec1/0
<ipython-input-16-89c6bf39c27a>:2: RuntimeWarning: invalid value encountered in true_divide
  vec2=vec1/0


In [37]:
vec1 = np.zeros((2,2))
print(vec1)

[[0. 0.]
 [0. 0.]]


In [38]:
mat1 = np.random.randn(3,3)
print(mat1)

[[ 0.37407468 -0.93796944 -0.06593474]
 [ 0.85295025  0.06239812  0.35763079]
 [-0.10513067  2.57648286  2.18807253]]
